spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
app:
  secret:
    key: YW5kcmV3SXNUaGVCZXN0SW5UaGVXb3JsZFlvdVNob3VsZExvdmVIaW0=
    lifetime: 86400000


